/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_LIB_GROVECOLOURSENSOR_H
#define _JERRYSCRIPT_MBED_LIB_GROVECOLOURSENSOR_H

#include "mbed-js-grovecoloursensor/mbed-js-grovecoloursensor.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

void mbed_js_GroveColourSensor_setup();

DECLARE_JS_WRAPPER_REGISTRATION (grovecoloursensor)
{
    REGISTER_CLASS_CONSTRUCTOR(GroveColourSensor);
    mbed_js_GroveColourSensor_setup();
}

#endif // _JERRYSCRIPT_MBED_LIB_GROVECOLOURSENSOR_H
