/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#ifndef _JERRYSCRIPT_MBED_GROVECOLOURSENSOR_H
#define _JERRYSCRIPT_MBED_GROVECOLOURSENSOR_H

#include "jerryscript-mbed-library-registry/wrap_tools.h"

#include "GroveColourSensor.hpp"

DECLARE_CLASS_CONSTRUCTOR(GroveColourSensor);
jerry_value_t mbed_js_wrap_native_object(GroveColourSensor* ptr);

#endif // _JERRYSCRIPT_MBED_GROVECOLOURSENSOR_H
