/* Generated by https://github.com/janjongboom/mbed-js-wrapper-generator */

#include "jerryscript-mbed-util/logging.h"
#include "jerryscript-mbed-library-registry/wrap_tools.h"

// @todo: add a reference to the GroveColourSensor header here

/**
 * GroveColourSensor#powerUp (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(GroveColourSensor, powerUp) {
    CHECK_ARGUMENT_COUNT(GroveColourSensor, powerUp, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        GroveColourSensor* native_ptr = reinterpret_cast<GroveColourSensor*>(ptr_val);
    
    
    
        native_ptr->powerUp();
        return jerry_create_undefined();
    }
}

/**
 * GroveColourSensor#powerDown (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(GroveColourSensor, powerDown) {
    CHECK_ARGUMENT_COUNT(GroveColourSensor, powerDown, (args_count == 0));

    if (args_count == 0) {
    
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        GroveColourSensor* native_ptr = reinterpret_cast<GroveColourSensor*>(ptr_val);
    
    
    
        native_ptr->powerDown();
        return jerry_create_undefined();
    }
}

/**
 * GroveColourSensor#readColour (native JavaScript method)
 */
DECLARE_CLASS_FUNCTION(GroveColourSensor, readColour) {
    CHECK_ARGUMENT_COUNT(GroveColourSensor, readColour, (args_count == 1) || (args_count == 1));

    if (args_count == 1) {
        CHECK_ARGUMENT_TYPE_ON_CONDITION(GroveColourSensor, readColour, 0, number, (args_count == 1));
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        GroveColourSensor* native_ptr = reinterpret_cast<GroveColourSensor*>(ptr_val);
    
        Colour_t arg0 = Colour_t(jerry_get_number_value(args[0]));
    
        uint16_t result = native_ptr->readColour(arg0);
        return jerry_create_number(result);
    }
    if (args_count == 1) {
        CHECK_ARGUMENT_TYPE_ON_CONDITION(GroveColourSensor, readColour, 0, number, (args_count == 1));
    
        uintptr_t ptr_val;
        jerry_get_object_native_handle(this_obj, &ptr_val);
    
        GroveColourSensor* native_ptr = reinterpret_cast<GroveColourSensor*>(ptr_val);
    
        double jArg0 = jerry_get_number_value(args[0]);
        unsigned int arg0 = static_cast<unsigned int>(jArg0);
    
        uint16_t result = native_ptr->readColour(arg0);
        return jerry_create_number(result);
    }
}

/**
 * GroveColourSensor#destructor
 *
 * Called if/when the GroveColourSensor is GC'ed.
 */
void NAME_FOR_CLASS_NATIVE_DESTRUCTOR(GroveColourSensor)(const uintptr_t native_handle) {
    delete reinterpret_cast<GroveColourSensor*>(native_handle);
}


/**
 * mbed_js_wrap_native_object (turns a native GroveColourSensor object into a JS object)
 */
jerry_value_t mbed_js_wrap_native_object(GroveColourSensor* ptr) {
    uintptr_t native_ptr = (uintptr_t) ptr;

    jerry_value_t js_object = jerry_create_object();
    jerry_set_object_native_handle(js_object, native_ptr, NAME_FOR_CLASS_NATIVE_DESTRUCTOR(GroveColourSensor));

    ATTACH_CLASS_FUNCTION(js_object, GroveColourSensor, powerUp);
    ATTACH_CLASS_FUNCTION(js_object, GroveColourSensor, powerDown);
    ATTACH_CLASS_FUNCTION(js_object, GroveColourSensor, readColour);

    return js_object;
}

/**
 * GroveColourSensor (native JavaScript constructor)
 */
DECLARE_CLASS_CONSTRUCTOR(GroveColourSensor) {
    CHECK_ARGUMENT_COUNT(GroveColourSensor, __constructor, (args_count == 2));

    if (args_count == 2) {
        CHECK_ARGUMENT_TYPE_ON_CONDITION(GroveColourSensor, __constructor, 0, number, (args_count == 2));
        CHECK_ARGUMENT_TYPE_ON_CONDITION(GroveColourSensor, __constructor, 1, number, (args_count == 2));
    
        PinName arg0 = PinName(jerry_get_number_value(args[0]));
        PinName arg1 = PinName(jerry_get_number_value(args[1]));
    
        // Create the native object
        GroveColourSensor* native_obj = new GroveColourSensor(arg0, arg1);
    
        return mbed_js_wrap_native_object(native_obj);
    }
}

void mbed_js_GroveColourSensor_setup() {

}
